# Generated by Django 3.0.6 on 2023-03-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230302_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date', '-published'], 'verbose_name': 'Article'},
        ),
    ]
