# Generated by Django 3.1.6 on 2023-03-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='Category',
            new_name='category',
        ),
    ]
